// Generated by `python3 -m topopaper.themes` from topopaper/themes.py.
// Do not edit by hand.
#pragma once

#define THEME_NROLES 19
enum { TR_BG_LO, TR_BG_HI, TR_LINE_LO, TR_LINE_HI, TR_WATER, TR_SHORE, TR_SNOW, TR_WARM, TR_RIM, TR_ICE, TR_INK_HALO, TR_INK, TR_CITY, TR_ROAD, TR_SKI, TR_LIFT, TR_BORDER, TR_AURORA_A, TR_AURORA_B };
static const char *theme_names[] = { "macchiato", "mocha", "nord", "gruvbox", "tokyonight", "graphite" };
#define THEME_COUNT 6
static const float theme_rgb[THEME_COUNT][THEME_NROLES][3] = {
    { // macchiato
        { 0.118f, 0.125f, 0.188f }, // bg_lo
        { 0.141f, 0.153f, 0.227f }, // bg_hi
        { 0.212f, 0.227f, 0.310f }, // line_lo
        { 0.286f, 0.302f, 0.392f }, // line_hi
        { 0.165f, 0.225f, 0.335f }, // water
        { 0.402f, 0.502f, 0.627f }, // shore
        { 0.845f, 0.865f, 0.920f }, // snow
        { 0.961f, 0.663f, 0.498f }, // warm
        { 0.300f, 0.450f, 0.620f }, // rim
        { 0.130f, 0.145f, 0.180f }, // ice
        { 0.094f, 0.098f, 0.145f }, // ink_halo
        { 0.722f, 0.753f, 0.878f }, // ink
        { 1.000f, 0.800f, 0.550f }, // city
        { 0.961f, 0.663f, 0.498f }, // road
        { 0.490f, 0.769f, 0.894f }, // ski
        { 0.929f, 0.529f, 0.588f }, // lift
        { 0.502f, 0.529f, 0.635f }, // border
        { 0.300f, 0.780f, 0.520f }, // aurora_a
        { 0.580f, 0.420f, 0.720f }, // aurora_b
    },
    { // mocha
        { 0.094f, 0.094f, 0.145f }, // bg_lo
        { 0.118f, 0.118f, 0.180f }, // bg_hi
        { 0.192f, 0.196f, 0.267f }, // line_lo
        { 0.271f, 0.278f, 0.353f }, // line_hi
        { 0.149f, 0.188f, 0.290f }, // water
        { 0.424f, 0.498f, 0.659f }, // shore
        { 0.835f, 0.859f, 0.941f }, // snow
        { 0.980f, 0.702f, 0.529f }, // warm
        { 0.302f, 0.451f, 0.627f }, // rim
        { 0.125f, 0.125f, 0.180f }, // ice
        { 0.067f, 0.067f, 0.106f }, // ink_halo
        { 0.729f, 0.761f, 0.871f }, // ink
        { 1.000f, 0.800f, 0.549f }, // city
        { 0.980f, 0.702f, 0.529f }, // road
        { 0.455f, 0.780f, 0.925f }, // ski
        { 0.953f, 0.545f, 0.659f }, // lift
        { 0.498f, 0.518f, 0.612f }, // border
        { 0.302f, 0.780f, 0.522f }, // aurora_a
        { 0.580f, 0.439f, 0.722f }, // aurora_b
    },
    { // nord
        { 0.141f, 0.161f, 0.200f }, // bg_lo
        { 0.180f, 0.204f, 0.251f }, // bg_hi
        { 0.231f, 0.259f, 0.322f }, // line_lo
        { 0.298f, 0.337f, 0.416f }, // line_hi
        { 0.184f, 0.239f, 0.322f }, // water
        { 0.427f, 0.533f, 0.659f }, // shore
        { 0.847f, 0.871f, 0.914f }, // snow
        { 0.816f, 0.529f, 0.439f }, // warm
        { 0.369f, 0.506f, 0.675f }, // rim
        { 0.169f, 0.192f, 0.235f }, // ice
        { 0.122f, 0.137f, 0.169f }, // ink_halo
        { 0.847f, 0.871f, 0.914f }, // ink
        { 0.922f, 0.796f, 0.545f }, // city
        { 0.816f, 0.529f, 0.439f }, // road
        { 0.533f, 0.753f, 0.816f }, // ski
        { 0.749f, 0.380f, 0.416f }, // lift
        { 0.506f, 0.631f, 0.757f }, // border
        { 0.639f, 0.745f, 0.549f }, // aurora_a
        { 0.706f, 0.557f, 0.678f }, // aurora_b
    },
    { // gruvbox
        { 0.114f, 0.125f, 0.129f }, // bg_lo
        { 0.157f, 0.157f, 0.157f }, // bg_hi
        { 0.235f, 0.220f, 0.212f }, // line_lo
        { 0.314f, 0.286f, 0.271f }, // line_hi
        { 0.137f, 0.200f, 0.227f }, // water
        { 0.435f, 0.561f, 0.533f }, // shore
        { 0.922f, 0.859f, 0.698f }, // snow
        { 0.996f, 0.502f, 0.098f }, // warm
        { 0.271f, 0.522f, 0.533f }, // rim
        { 0.165f, 0.157f, 0.149f }, // ice
        { 0.078f, 0.086f, 0.090f }, // ink_halo
        { 0.835f, 0.769f, 0.631f }, // ink
        { 0.980f, 0.741f, 0.184f }, // city
        { 0.996f, 0.502f, 0.098f }, // road
        { 0.514f, 0.647f, 0.596f }, // ski
        { 0.984f, 0.286f, 0.204f }, // lift
        { 0.573f, 0.514f, 0.455f }, // border
        { 0.557f, 0.753f, 0.486f }, // aurora_a
        { 0.827f, 0.525f, 0.608f }, // aurora_b
    },
    { // tokyonight
        { 0.086f, 0.086f, 0.118f }, // bg_lo
        { 0.102f, 0.106f, 0.149f }, // bg_hi
        { 0.161f, 0.180f, 0.259f }, // line_lo
        { 0.231f, 0.259f, 0.380f }, // line_hi
        { 0.122f, 0.165f, 0.267f }, // water
        { 0.353f, 0.435f, 0.659f }, // shore
        { 0.753f, 0.792f, 0.961f }, // snow
        { 1.000f, 0.620f, 0.392f }, // warm
        { 0.239f, 0.349f, 0.631f }, // rim
        { 0.110f, 0.114f, 0.161f }, // ice
        { 0.059f, 0.059f, 0.078f }, // ink_halo
        { 0.663f, 0.694f, 0.839f }, // ink
        { 0.878f, 0.686f, 0.408f }, // city
        { 1.000f, 0.620f, 0.392f }, // road
        { 0.490f, 0.812f, 1.000f }, // ski
        { 0.969f, 0.463f, 0.557f }, // lift
        { 0.337f, 0.373f, 0.537f }, // border
        { 0.451f, 0.855f, 0.792f }, // aurora_a
        { 0.733f, 0.604f, 0.969f }, // aurora_b
    },
    { // graphite
        { 0.086f, 0.086f, 0.086f }, // bg_lo
        { 0.118f, 0.118f, 0.118f }, // bg_hi
        { 0.200f, 0.200f, 0.200f }, // line_lo
        { 0.278f, 0.278f, 0.278f }, // line_hi
        { 0.149f, 0.165f, 0.180f }, // water
        { 0.478f, 0.510f, 0.533f }, // shore
        { 0.863f, 0.863f, 0.863f }, // snow
        { 0.784f, 0.784f, 0.784f }, // warm
        { 0.353f, 0.353f, 0.353f }, // rim
        { 0.133f, 0.133f, 0.133f }, // ice
        { 0.055f, 0.055f, 0.055f }, // ink_halo
        { 0.776f, 0.776f, 0.776f }, // ink
        { 0.902f, 0.847f, 0.722f }, // city
        { 0.741f, 0.741f, 0.741f }, // road
        { 0.624f, 0.706f, 0.769f }, // ski
        { 0.769f, 0.624f, 0.624f }, // lift
        { 0.541f, 0.541f, 0.541f }, // border
        { 0.561f, 0.749f, 0.627f }, // aurora_a
        { 0.659f, 0.624f, 0.749f }, // aurora_b
    },
};
