"""Colour themes: the one source of truth.

The engine compiles these in via engine/themes.h, generated by
`python3 -m topopaper.themes > engine/themes.h` (a test keeps the two in
sync). The settings app reads them for its swatches.

Roles:
    bg_lo, bg_hi       background gradient (bottom, top)
    line_lo, line_hi   contour lines, low to high elevation
    water, shore       lake/ocean fill and shoreline stroke
    snow               snow tint above the snowline
    warm               tint the lines take on while the CPU is busy
    rim                glow at the globe's edge
    ice                polar ice caps
    ink_halo, ink      label and HUD text: halo and fill
    city               night-side city lights
    road, ski, lift    pack features (roads, ski runs, ski lifts)
    border             state/province borders
    aurora_a, aurora_b aurora gradient
"""
import sys

ROLES = ("bg_lo", "bg_hi", "line_lo", "line_hi", "water", "shore", "snow", "warm",
         "rim", "ice", "ink_halo", "ink", "city", "road", "ski", "lift", "border",
         "aurora_a", "aurora_b")


def _hex(h):
    h = h.lstrip("#")
    return tuple(round(int(h[i:i + 2], 16) / 255.0, 3) for i in (0, 2, 4))


def _theme(label, **roles):
    out = {"label": label}
    for r in ROLES:
        v = roles[r]
        out[r] = _hex(v) if isinstance(v, str) else tuple(v)
    return out


THEMES = {
    # the original palette (Catppuccin Macchiato), values exactly as tuned
    "macchiato": _theme(
        "Catppuccin Macchiato",
        bg_lo=(0.118, 0.125, 0.188), bg_hi=(0.141, 0.153, 0.227),
        line_lo=(0.212, 0.227, 0.310), line_hi=(0.286, 0.302, 0.392),
        water=(0.165, 0.225, 0.335), shore=(0.402, 0.502, 0.627),
        snow=(0.845, 0.865, 0.920), warm=(0.961, 0.663, 0.498),
        rim=(0.30, 0.45, 0.62), ice=(0.13, 0.145, 0.18),
        ink_halo=(0.094, 0.098, 0.145), ink=(0.722, 0.753, 0.878),
        city=(1.0, 0.80, 0.55), road=(0.961, 0.663, 0.498),
        ski=(0.490, 0.769, 0.894), lift=(0.929, 0.529, 0.588),
        border=(0.502, 0.529, 0.635),
        aurora_a=(0.30, 0.78, 0.52), aurora_b=(0.58, 0.42, 0.72)),
    "mocha": _theme(
        "Catppuccin Mocha",
        bg_lo="#181825", bg_hi="#1e1e2e", line_lo="#313244", line_hi="#45475a",
        water="#26304a", shore="#6c7fa8", snow="#d5dbf0", warm="#fab387",
        rim="#4d73a0", ice="#20202e", ink_halo="#11111b", ink="#bac2de",
        city="#ffcc8c", road="#fab387", ski="#74c7ec", lift="#f38ba8",
        border="#7f849c", aurora_a="#4dc785", aurora_b="#9470b8"),
    "nord": _theme(
        "Nord",
        bg_lo="#242933", bg_hi="#2e3440", line_lo="#3b4252", line_hi="#4c566a",
        water="#2f3d52", shore="#6d88a8", snow="#d8dee9", warm="#d08770",
        rim="#5e81ac", ice="#2b313c", ink_halo="#1f232b", ink="#d8dee9",
        city="#ebcb8b", road="#d08770", ski="#88c0d0", lift="#bf616a",
        border="#81a1c1", aurora_a="#a3be8c", aurora_b="#b48ead"),
    "gruvbox": _theme(
        "Gruvbox Dark",
        bg_lo="#1d2021", bg_hi="#282828", line_lo="#3c3836", line_hi="#504945",
        water="#23333a", shore="#6f8f88", snow="#ebdbb2", warm="#fe8019",
        rim="#458588", ice="#2a2826", ink_halo="#141617", ink="#d5c4a1",
        city="#fabd2f", road="#fe8019", ski="#83a598", lift="#fb4934",
        border="#928374", aurora_a="#8ec07c", aurora_b="#d3869b"),
    "tokyonight": _theme(
        "Tokyo Night",
        bg_lo="#16161e", bg_hi="#1a1b26", line_lo="#292e42", line_hi="#3b4261",
        water="#1f2a44", shore="#5a6fa8", snow="#c0caf5", warm="#ff9e64",
        rim="#3d59a1", ice="#1c1d29", ink_halo="#0f0f14", ink="#a9b1d6",
        city="#e0af68", road="#ff9e64", ski="#7dcfff", lift="#f7768e",
        border="#565f89", aurora_a="#73daca", aurora_b="#bb9af7"),
    "graphite": _theme(
        "Graphite",
        bg_lo="#161616", bg_hi="#1e1e1e", line_lo="#333333", line_hi="#474747",
        water="#262a2e", shore="#7a8288", snow="#dcdcdc", warm="#c8c8c8",
        rim="#5a5a5a", ice="#222222", ink_halo="#0e0e0e", ink="#c6c6c6",
        city="#e6d8b8", road="#bdbdbd", ski="#9fb4c4", lift="#c49f9f",
        border="#8a8a8a", aurora_a="#8fbfa0", aurora_b="#a89fbf"),
}

# Packs bake their feature colours into meta.bin using the macchiato values;
# the engine recognises those and swaps in the active theme's role.
BAKED_KEYS = ("road", "ski", "lift", "border")


def c_header():
    out = ["// Generated by `python3 -m topopaper.themes` from topopaper/themes.py.",
           "// Do not edit by hand.", "#pragma once", "",
           f"#define THEME_NROLES {len(ROLES)}",
           "enum { " + ", ".join(f"TR_{r.upper()}" for r in ROLES) + " };",
           "static const char *theme_names[] = { "
           + ", ".join(f'"{n}"' for n in THEMES) + " };",
           f"#define THEME_COUNT {len(THEMES)}",
           "static const float theme_rgb[THEME_COUNT][THEME_NROLES][3] = {"]
    for name, t in THEMES.items():
        out.append(f"    {{ // {name}")
        for r in ROLES:
            c = t[r]
            out.append(f"        {{ {c[0]:.3f}f, {c[1]:.3f}f, {c[2]:.3f}f }}, // {r}")
        out.append("    },")
    out.append("};")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    sys.stdout.write(c_header())
